# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
# Download the pgp keys from azure secure library
- task: DownloadSecureFile@1
  displayName: 'Get secring.asc from Azure Secure Library'
  inputs:
    secureFile: "secring.asc"

- task: DownloadSecureFile@1
  displayName: 'Get pubring.asc from Azure Secure Library'
  inputs:
    secureFile: "pubring.asc"    

- script: |
    mkdir -p /tmp/pgp && \
    cp $(DownloadSecureFile1.secureFilePath) /tmp/pgp && \
    cp $(DownloadSecureFile2.secureFilePath) /tmp/pgp
  displayName: 'Move pgp keys'  

- script: |
    docker-compose -f src/it/resources/docker-compose.yml up --build -d
  displayName: 'Create a docker-compose based testing environment'

- script: |
    docker exec \
    -w /app \
    sbt \
    sbt test
  displayName: 'Run sbt test'

- script: |
    docker exec \
    -w /app \
    sbt \
    sbt it:test
  displayName: 'Tun sbt it:test'  

- script: |
    docker exec \
    -w /app \
    sbt \
    sbt publishSigned
  displayName: 'Run sbt publishSigned (push to https://oss.sonatype.org/content/groups/staging/)'
