# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker build . -t scala-sbt:latest -f BuildDockerfile 
  displayName: 'Build the scala-sbt docker image'

- script: |
    docker run --rm -v $(pwd):/sbt scala-sbt:latest sbt test
  displayName: 'Run arc test'
