# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker run --rm -v $(pwd):/app -w /app mozilla/sbt:8u212_1.2.8 sbt test
  displayName: 'Run arc test'