---
version: '3.5'

networks:
  arc-integration:
    name: arc-integration
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - arc-integration
    ports: 
        - 32181:32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - arc-integration
    ports:
        - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENERS: CLIENT://0.0.0.0:29092,INTERNAL://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: CLIENT://localhost:29092,INTERNAL://kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 10
  
  kafka-rest:
    image: confluentinc/cp-kafka-rest:latest
    networks:
      - arc-integration
    ports:
      - 8082:8082
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:29093
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082

  tensorflow_serving:
    image: tensorflow_serving/simple:latest
    networks:
      - arc-integration    
    build: tensorflow_serving/.
    ports:
      - 9000:9000
      - 9001:9001

  sqlserver:
    image: microsoft/mssql-server-linux:2017-CU9
    networks:
      - arc-integration    
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "SecretPass!2018"
      MSSQL_PID: Express

  postgres:
    image: postgres:10.4-alpine-init
    networks:
      - arc-integration    
    build: postgres/.
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: "SecretPass!2018"

  flask_serving:
    image: flask_serving/simple:latest
    networks:
      - arc-integration    
    build: flask_serving/.
    ports:
      - 5000:5000